Update to version $i

diff --git a/bin/git_repo b/bin/git_repo
--- a/bin/git_repo
+++ b/bin/git_repo
@@ -12,18 +12,21 @@ prog=`basename $0`
 git_server=git@github-bsn.broadcom.com
 repo=bsnfos.git
 
+swrel=/zzz/work00/swrel
+
 usage="Usage: $prog [<options>] [<repo>]
 
  Options:
    -usr <name>          - Search for name and use that users workspace
    -remote-repo <repo>  - Specify the remote GIT repo (default:$repo) when cloning
    -repo <path>         - Specify full path to workspace and repo to use
+   -nightly <pat>       - Look for repo matching <pat> in swrel nightly build path
 "
 
 find_depth=4
 
 sopts="u:h"
-lopts="usr:,user:,remote-repo:,repo:,help"
+lopts="usr:,user:,remote-repo:,repo:,nightly:,help"
 
 optarg=0
 opts=`getopt -n $prog -o $sopts -ual $lopts -- $@`
@@ -61,6 +64,11 @@ while [ $1 != -- ]; do
 			git_path=`dirname $full_path`
 			;;
 
+		--nightly)
+			pattern=$2
+			shift
+			;;
+
 		-h | --help)
 			echo ""
 			echo "$usage"
@@ -95,6 +103,30 @@ if [ $usr_srch ]; then
 		$usermap $usr_srch
 		read -p  "Please enter user OktaID: " usr
 	fi
+fi
+
+# If doing a nightly build search pattern
+if [ $pattern ]; then
+	srch=`find ${swrel} -maxdepth ${find_depth} | grep ${pattern}`
+	num_paths=0
+	for path in ${srch}; do
+		if [ -e ${path}/.git ]; then
+			echo "${path}"
+			full_path=${path}
+			let num_paths+=1
+		fi
+	done
+	if [ $num_paths -eq 0 ]; then
+		echo "Pattern ${pattern} not found"
+		exit 1
+	fi
+	if [ $num_paths -gt 1 ]; then
+		echo "Multiple repositories found matching:${pattern}. Please specify which repository."
+		echo ""
+		read -p "Please enter repository path: " full_path
+	fi
+	git_repo=`basename $full_path`
+	git_path=`dirname $full_path`
 fi
 
 # Define the workspace for the specified user
