Update dotfiles for cleaner .rc shell setup
This will now use a single .rc/ directory for all the shell resource scripts. All are loaded in a tiered order based on the name prefix, while still allowing for unordered file loading. New resource scripts can be added in as needed either through symlinks or direct file creation.

diff --git a/sbin/bld-target b/sbin/bld-target
--- a/sbin/bld-target
+++ b/sbin/bld-target
@@ -1,6 +1,14 @@
 #!/bin/bash
 #
 
+bld_target_resolve=/home/dh404494/bin/bld_target_resolve.bash
+if [ -f $bld_target_resolve ]; then
+	. $bld_target_resolve
+else
+	echo "ERROR: Could not load bld_target_resolve [$bld_target_resolve]" >&2
+	exit 1
+fi
+
 prog=$(basename "$0")
 
 usage="Target Usage: $prog [<options>]
@@ -20,10 +28,11 @@ if [[ -z "$BLD_TARGET_SCRIPT" ]]; then
 	if [[ $GITRC_ENVIRONMENT == 1 && -n "$GIT_ROOT" ]]; then
 		target_rc=${GIT_ROOT}/.rc/bld_target.sh
 	else
-		if [[ ! -d $HOME/bin/prompt_command ]]; then
-			mkdir -p $HOME/bin/prompt_command
+		target_rc=$(resolve_bld_target_file)
+		if [[ -z "$target_rc" ]]; then
+			echo "ERROR: Could not find or determine a location for bld_target.sh (checked ~/.rc/prompt.d, ~/.private, ~/bin/prompt_command)." >&2
+			exit 1
 		fi
-		target_rc=${HOME}/bin/prompt_command/bld_target.sh
 	fi
 else
 	target_rc=$BLD_TARGET_SCRIPT
